### ISSUE TITLE
Make subject/issuer required

### ISSUE THREAD

**Issue by vaikas** [sigstore/policy-controller#107]
**Description**

TL;DR not specifying issuer/subject is bad, we should not allow folks to craft CIPs that do not specify those. More details here:
https://docs.google.com/document/d/1o8_bXIygufgiohJGlmBzqF4_BnXCTfgh4ILgJFJxYRs/edit?resourcekey=0-YEar3v67uoT31kj83dCVvA#heading=h.oiw6nn1ucgaq

**Comment by hectorj2f** [comment]
@vaikas I started working on this, do we want to make required the subject and issuer on any keyless configuration ?

**Comment by hectorj2f** [comment]
https://github.com/sigstore/policy-controller/pull/125 I opened a draft PR,
do we want to require the issuer and subject whenever a CaCert is not defined ?

**Comment by vaikas** [comment]
That's a great question and I was wondering about that as well. From the original design document, it was described as this, but I honestly don't think this has even been implemented or documented or tested?
```
# For air-gapped scenarios, we support identifying the
      # relevant keys local to the cluster, either via inline
      # public-key data, or a secretRef (in the cosign-system
      # namespace).  Each of these share a shape with the
      # "key" field above.
      ca-cert:
	   name: # arbitrary identifier
        data: # inline public key data
```
... time passes ... Yeah, so it's not documented, nor is it implemented. Maybe we should ask some of the folks from the task force for what the purpose / usage was and how does it play with keyless. Maybe @mattmoor remembers?
I kind of feel that if it's not implemented, we might want to actually reject that field now, because it's a poor user experience, or we should implement it and add tests for it.
