### ISSUE TITLE
Verify only pods

### ISSUE THREAD

**Issue by dszakallas** [sigstore/policy-controller#1388]
**Description**

Make policy-controller configurable to only consider pods, not higher level resources. 

### Use case

We are using a continuous reconciliation (GitOps) solution, Flux, to maintain cluster state. The mutation of the image reference  by the mutating admission webhook has indesired effects for us when used in conjunction with Flux:
- Jobs are immutable. It can happen that digest changes for the same tag between reconciliations, causing an mutation to happen to a job, which is rejected by kube api server.
- even for deployments, resolving a digest every sync cycle causes a tight control that forces redeployment whenever the digest changes behind a tag, which we find undesirable.

### Workarounds

While the scope of resources to validate can be controlled on the Policy level, this is not sufficient for our use, as mutations still get applied to all recognized resources and this [seems to be hard coded](https://github.com/sigstore/policy-controller/blob/main/cmd/webhook/main.go#L202-L209). Eventually, the only workaround I found was to fork the code and remove these, alond with their corresponding resource names.

### Relwork

Correctly me if I am wrong, but I believe this change would not deteriorate the integrity of the cluster, since the pods owned by these unvalidated resources would still go through admission control, and their images will be verified. As an example of this practice, PSA (Pod Security Admission) only operates on the pod resource. Recently, Connaisseur also [added a flag](https://github.com/sse-secure-systems/connaisseur/releases/tag/v3.4.0) to opt out of higher level resource validation.

**Comment by senanz** [comment]
@hectorj2f - could you please assign it to me, started to work on code that supporting that.

**Comment by 0xiso** [comment]
@senanz We are also facing the same issue and are searching for solutions. Seems like you are working on solving this problem, but do you have plans to create a PR?

**Comment by hectorj2f** [comment]
@0xiso @senanz feel free to assign it yourself, but we need to discuss whether we want to go ahead with this change.

**Comment by senanz** [comment]
@hectorj2f - I have already have the change, need to do some modification and let's discuss that then.
will update you soon.
Thanks for consering that.

**Comment by senanz** [comment]
@0xiso - I have the PR need some updates and will raise it again.
@hectorj2f -Could you please assign the ticket on me?

**Comment by senanz** [comment]
@hectorj2f - Could you please review?
https://github.com/sigstore/policy-controller/pull/1687
Let me know of you want to do dsicussion regarding that on slack.

**Comment by Cajga** [comment]
The reality is that most of the Open Source projects do not use digests but more and more use Cosign signatures. Even the ones who care about security like Istio. You can verify their image provenance through their signatures but their deployment still use versioned tags:
```
$ kubectl get deployments.apps -n istio-system istiod -o yaml|grep image
        image: docker.io/istio/pilot:1.26.2
        imagePullPolicy: IfNotPresent
```

With the increased adoption of GitOps (being it ArgoCD of Flux), the fact that policy controller is not compatible with such deployments makes it less and less useful.

Just to have the related tickets linked and collected in one place:
* https://github.com/sigstore/policy-controller/issues/1388
* https://github.com/sigstore/policy-controller/issues/745
* https://github.com/sigstore/policy-controller/issues/285

**Comment by Cajga** [comment]
In fact, this is not an issue anymore and I am sorry for commenting without testing. **Flux is using server-side apply and server-side diff/dry-run to check whether there is reconciliation needed. This means that mutation is applied when the dry-run happens and as such it does not see this as diff.**

Consider the following example in which I modify the image tag by decreasing the version with one and flux will show the whole diff (including the digest that the policy-controller mutated for the deployment):
```
$ grep newTag kustomization.yaml
  newTag: 0.2.7
$ flux diff kustomization -n gitops-exampleapp-kustomize-dev exampleapp-on-gitlabx --path ./
✓  Kustomization diffing...
$ vim kustomization.yaml                             
$ grep newTag kustomization.yaml
  newTag: 0.2.6
$ flux diff kustomization -n gitops-exampleapp-kustomize-dev exampleapp-on-gitlabx --path ./
✓  Kustomization diffing...
► Deployment/app-exampleapp-kustomize-dev/exampleapp drifted

metadata.generation
  ± value change
    - 19
    + 20

spec.template.spec.containers.exampleapp.image
  ± value change
    - registry.example.com/exampleapp/exampleapp:0.2.7@sha256:33afd163a71de7f9452acf72bffe268e4a1ae04a878b0ba279f86d9776275e51
    + registry.example.com/exampleapp/exampleapp:0.2.6@sha256:9f5ae129a12bebf08d001cca4d57d9b4c9a2f7d1fa0f378a67b5bf96af339f8a

⚠️ identified at least one change, exiting with non-zero exit code
$
```

ArgoCD also supports server-side apply (I do not have any mean to test it now)...

**Comment by alxivanov** [comment]
With Openshift Service Mesh 3 (Istio downstream), the Ingress Gateway deployment is using the static image reference value "auto". The exact image reference is supplied to the pod by the operator during rollout, and is thus not known to the deployment. This makes it impossible to deploy with the default webhook configurations that validate deployments: 
```
Error from server (BadRequest): error when creating "istio-ingressgateway-deployment.yaml": 
admission webhook "policy.sigstore.dev" denied the request: validation failed: invalid value: 
auto must be an image digest: spec.template.spec.containers[0].image
```

Using extracted image digest from a pod deployed to an unenforced namespace is not a desired solution as this will require manual update to all Ingress Gateway deployments during SM 3 updates. 

Temporary workaround is to create custom validating and mutating webhook configurations that target pods only. This solution has a significant drawback - the certificate used during webhook authentication is valid for only 1 week, then rerolled. This requires it to be manually applied to the custom webhook configurations once a week. A cronjob that extracts a fresh copy of the certificate after it has been rerolled, and subsequently applies it to the custom webhook configurations can be used. 

Proposed soultion: allow webhook configuration rules to be controlled through `.Values.webhook.rules`:
```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ required "A valid cosign.webhookName is required" .Values.cosign.webhookName }}
webhooks:
- name: {{ required "A valid cosign.webhookName is required" .Values.cosign.webhookName }}
  namespaceSelector:
{{- include "policy-controller.webhook.namespaceSelector" . | indent 4 }}
  admissionReviewVersions: [v1]
  clientConfig:
    service:
      name: webhook
      namespace: {{ .Release.Namespace }}
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  sideEffects: None
  {{- if .Values.cosign.webhookTimeoutSeconds }}
  {{- if .Values.cosign.webhookTimeoutSeconds.validating }}
  timeoutSeconds: {{ .Values.cosign.webhookTimeoutSeconds.validating }}
  rules:
  {{ .Values.webhook.rules }}
  {{- end }}
  {{- end}}
```
Rules can then be specified as:
```
        webhook:
          rules:
            validatingWebhookConfiguration:
            - apiGroups: [""]
              apiVersions: ["v1"]
              operations: ["CREATE", "UPDATE"]
              resources: ["pods"]
            mutatingWebhookConfiguration:
            - apiGroups: [""]
              apiVersions: ["v1"]
              operations: ["CREATE", "UPDATE"]
              resources: ["pods"]
```
