### ISSUE TITLE
Support for Sigstore Bundle Specification

### ISSUE THREAD

**Issue by codysoyland** [sigstore/policy-controller#1406]
**Description**

Policy-Controller currently supports verification of attestations/signatures generated using `cosign sign`/`cosign attest`, which attach signatures/attestations using the process described in the [Cosign Signature Specification](https://github.com/sigstore/cosign/blob/main/specs/SIGNATURE_SPEC.md#storage). In summary, this signature attachment scheme utilizes a Tag-based discovery mechanism where an image manifest ([OCI Image Manifest V1](https://github.com/sigstore/cosign/blob/main/specs/SIGNATURE_SPEC.md#oci-image-manifest-v1)) is created to reference a specific image digest, and each layer references a payload in the [Simple Signing](https://github.com/containers/image/blob/a5061e5a5f00333ea3a92e7103effd11c6e2f51d/docs/containers-signature.5.md#json-data-format) format. Other data needed to perform verification is stored in annotations on the layer descriptor.

A [newer specification for storing Sigstore Bundles](https://github.com/sigstore/cosign/blob/main/specs/BUNDLE_SPEC.md) has been accepted, which utilizes the OCI 1.1 Manifest Referrers API to attach [Sigstore Bundles](https://github.com/sigstore/protobuf-specs/blob/main/protos/sigstore_bundle.proto) as referring artifacts to an image, which simplifies the storage/retrieval of attestations/signatures and enables use of the newer generation of Sigstore clients (e.g. `sigstore-js`, `sigstore-python`, and `sigstore-go`) to verify Sigstore Bundles. `cosign` currently lacks that ability, but [there are plans](https://github.com/sigstore/cosign/issues/3139) to support it in the future. Additionally, [GitHub Artifact Attestations](https://docs.github.com/en/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds#generating-build-provenance-for-container-images) attach Sigstore Bundles following the spec, and Policy-Controller is currently unable to verify these attestations.

I would like to add support for verifying image signatures/attestations using the new bundle spec in Policy-Controller. In order to do so without breaking existing usage, I propose we add a `signatureFormat` property to the [Authority](https://github.com/sigstore/policy-controller/blob/main/docs/api-types/index-v1alpha1.md#authority) type, which could be one of `[simplesigning, bundle]` and would default to `simplesigning`. When the `authority` has the property `signatureFormat: bundle`, the controller would take an alternative code path which would implement the Sigstore Bundle spec to look up the attestations and verify them using `sigstore-go`. I am preparing a branch which implements the above scheme, and I hope to open a PR in the coming days.

**Comment by hectorj2f** [comment]
@codysoyland It sounds good. Could you share some examples of yaml definitions here? That would help to understand the changes.

**Comment by codysoyland** [comment]
@hectorj2f Of course! My proposed change to the yaml is the addition of `signatureFormat` in the `authorities` list.

Taking this example from [the docs](https://docs.sigstore.dev/policy-controller/overview/#configuring-policy-that-validates-attestations):

```yaml
apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: image-policy-keyless-with-attestations
spec:
  images:
  - glob: registry.local:5000/policy-controller/demo*
  authorities:
  - name: verify custom attestation
    keyless:
      url: http://fulcio.fulcio-system.svc
      identities:
      - issuerRegExp: .*kubernetes.default.*
        subjectRegExp: .*kubernetes.io/namespaces/default/serviceaccounts/default
    ctlog:
      url: http://rekor.rekor-system.svc
    attestations:
    - name: custom-match-predicate
      predicateType: https://cosign.sigstore.dev/attestation/v1
      policy:
        type: cue
        data: |
          predicateType: "https://cosign.sigstore.dev/attestation/v1"
          predicate: "foobar e2e test"
```

After my proposed changes, the above policy would continue to work as it always had: verify the attestation using the classic `cosign` verification flow.

If a user wished to verify a *Sigstore Bundle*, they would modify the above with a `signatureFormat` value set to `bundle`.  I have bolded the change to make it more clear:

<pre>
apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: image-policy-keyless-with-attestations
spec:
  images:
  - glob: registry.local:5000/policy-controller/demo*
  authorities:
  - name: verify custom attestation
    <b>signatureFormat: bundle</b>
    keyless:
      url: http://fulcio.fulcio-system.svc
      identities:
      - issuerRegExp: .*kubernetes.default.*
        subjectRegExp: .*kubernetes.io/namespaces/default/serviceaccounts/default
    ctlog:
      url: http://rekor.rekor-system.svc
    attestations:
    - name: custom-match-predicate
      predicateType: https://cosign.sigstore.dev/attestation/v1
      policy:
        type: cue
        data: |
          predicateType: "https://cosign.sigstore.dev/attestation/v1"
          predicate: "foobar e2e test"
</pre>
