### ISSUE TITLE
signaturePullSecrets ignored

### ISSUE THREAD

**Issue by ewuro** [sigstore/policy-controller#1625]
**Question**
We've installed the sigstore policy-controller on a Kubernetes cluster but it fails to pull an image signature from
our GitLab registry despite us having provided signaturePullSecrets. It appears to ignore the signaturePullSecret because
GitLab reports that the credentials configured in the secret have never been used. Could you please point out what we might be
doing wrong and suggest how we could get the verification to work?

Here's the error message we get:

Error: UPGRADE FAILED: failed to create resource: admission webhook "policy.sigstore.dev" denied the request:
validation failed: failed policy: magenta-cip: spec.template.spec.containers[0].image
<gitlab-registry-url>/<our_app>@sha256:<image_sig> signature key validation failed for authority magenta for
<gitlab-registry-url>/<our_app>@sha256:<image_sig>:
GET https://<gitlab-api-host>/jwt/auth?scope=repository%3A:<our-app>%3Apull&service=container_registry:
DENIED: access forbidden

Here too is our clusterimage policy:
```yaml
apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: magenta-cip
spec:
  images:
    - glob: "<my_image_filter"
  authorities:
    - name: magenta-auth
      key:
        secretRef: registry-cred
```
We run a local rekor instance and have successfully verified the the image signature in the same registry

Our environment:

1. Cosign v2.4.0
2. PolicyController installed using v0.7.0 Helm chart
3. Air-gapped Kubernetes 1.28.9 cluster
4. Local rekor v1.3.6 instance

**Comment by ewuro** [comment]
Please ignore the earlier cluster-image-policy, here's the correct version:
```yaml
apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: magenta-cip
spec:
  images:
    - glob: "<my_image_filter"
  authorities:
    - name: magenta-auth
      key:
        secretRef: cosign-pub
      source:
        - signaturePullSecrets:
            - name: registry-cred
```
