### ISSUE TITLE
Enhance ClusterImagePolicy with object and namespace selectors

### ISSUE THREAD

**Issue by vpnachev** [sigstore/policy-controller#18]
**Description**

Currently, the ClusterImagePolicy is applied based on glob matching the image. In some cases, this is not powerful enough to support k8s clusters running in something like a multi tenant mode where the tenants are free to use any OCI registry and each tenant brings own pair of cosign keys. 

Let's say we have the tenants `foo` and `bar`, each of them deploys own workload into the own namespaces `foo` and `bar` respectively. The cluster is installed with policy-controller and each of them can deploys own ClusterImagePolicy with their own public keys, 
```yaml
---
apiVersion: cosigned.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: foo
spec:
  images:
  - glob: *
  authorities:
  - name: foo
    key:
      data: |
        -----BEGIN PUBLIC KEY-----
        abcd...
---
apiVersion: cosigned.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: bar
spec:
  images:
  - glob: *
  authorities:
  - name: bar
    key:
      data: |
        -----BEGIN PUBLIC KEY-----
        1234...
```

In this way, the workload of `foo` must be verified with the key of `bar` which is not expected to succeed, therefore `foo`'s workload cannot be deployed. Same is valid for `bar` - `bar's workload must be admitted by the `foo`'s key which will fail. 

With namespace and object selectors in the CIP resource it should be fairly easy to limit the cosign signature verification of foo and bar to their own workload. 

I believe such feature should be useful also for single tenant cluster where images from multiple vendors are deployed and each vendor have own public keys. Of course, specifying all the keys in a single CIP resource is a possible solution, but the CIP can grown with the number of vendors and become cumbersome to manage instead of multiple CIPs.

PS. The discussion on this subject originally started at https://sigstore.slack.com/archives/C03096V09F1/p1654701745570749.
