### ISSUE TITLE
admit only from cosign.secretKeyRef.name, not from ClusterImagePolicy

### ISSUE THREAD

**Issue by dushasokol-tasks** [sigstore/policy-controller#193]
**Description**

Hello. Is it a bug, or just my mistake?

I am installing via helm, with `cosign.secretKeyRef.name=defaultsecret`.
I am generating another 'testsecret' secret

```
helm upgrade -i policy-controller -n cosign-system sigstore/policy-controller --devel --create-namespace --set cosign.secretKeyRef.name=defaultsecret

kubectl create ns my-secure-namespace

kubectl label namespace my-secure-namespace policy.sigstore.dev/include=true

cosign generate-key-pair k8s://cosign-system/testsecret

docker pull quay.io/rotorocloud/tools:jq

cosign sign --key k8s://cosign-system/testsecret quay.io/rotorocloud/tools:jq
```

After, I am applying a ClusterImagePolicy

```
apiVersion:   policy.sigstore.dev/v1beta1
kind:   ClusterImagePolicy
metadata:   
    name:   image-policy
spec:   
    images:
    - glob:   "**"
    authorities:
    - key:
          secretRef:
              name:   testsecret
```

Next, I am trying to create a pod

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secure-pod
  name: secure-pod
  namespace: my-secure-namespace
spec:
  containers:
  - image: quay.io/rotorocloud/tools:jq
```

kubect apply -f test-pod.yaml

_Error from server (BadRequest): error when creating "/root/test-pod.yaml": admission webhook "policy.sigstore.dev" denied the request: validation failed: no matching signatures:
invalid signature when validating ASN.1 encoded signature: spec.containers[0].image
quay.io/rotorocloud/tools@sha256:9dd297c1f04d8765d2b42f4e857a7c28e0d7c40f57ad511044ccbd9c79187bf2_

But if I sign it via default key from **cosign.secretKeyRef.name**

`cosign sign --key k8s://cosign-system/defaultsecret quay.io/rotorocloud/tools:jq`

kubect apply -f test-pod.yaml
_pod/secure-pod created_

It looks like policy-controller is not checking ClusterImagePolicy.
Or my policy is wrong.

**Version**

Its last policy-controller chart `https://github.com/sigstore/helm-charts/tree/main/charts/policy-controller`

ghcr.io/sigstore/policy-controller/policy-webhook@sha256:63cd54b877bcd8b3d6d6b7110955e3f773bd8ad5b16d1b6133d4009c26c6da18
