### ISSUE TITLE
Feature Request: Allow restriction of policy by namespace.

### ISSUE THREAD

**Issue by slimm609** [sigstore/policy-controller#298]
Today if you have multiple ClusterImagePolicy resources, there is no easy way to restrict them in a mutli-tenant environment by namespace. If you have 2 teams, `teamA` and `teamB`, they want to both sign their own images but only want images signed by their own key to run in their own namespace.  

```
apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: teamA
spec:
...
---
apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: teamB
spec:
...
```
Adding an additional label to be able to only allow validation against a specific policy,  would allow a reduced scope of which policy can be used to validate a specific namespace.
```
policy.sigstore.dev/policyName=teamA
```

This would cause anything from teamB to fail in the namespace that is only allowed to use the teamA policy.
