### ISSUE TITLE
Generate SLSA provenance

### ISSUE THREAD

**Issue by hectorj2f** [sigstore/policy-controller#446]
**Description**

Include slsa-provenance in our release pipeline:

```

  provenance:
    needs: [release]
    permissions:
      actions: read # To read the workflow path.
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.4.0
    with:
      base64-subjects: "${{ needs.release.outputs.hashes }}"
      upload-assets: true # upload to a new release
```
