### ISSUE TITLE
REGRESSION: new failure when `ctlog` is absent

### ISSUE THREAD

**Issue by mattmoor** [sigstore/policy-controller#479]
**Description**

The following policy works fine with the latest released version of things, but I noticed adding unit testing at HEAD that it fails(!)

```yaml
apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: ko-default-base-image-policy
spec:
  images:
  - glob: cgr.dev/chainguard/static*
  authorities:
  - keyless:
      url: https://fulcio.sigstore.dev
```

I see the following error:
```
signature keyless validation failed for authority authority-0 for cgr.dev/chainguard/static@sha256:39ae0654d64cb72003216f6148e581e6d7cf239ac32325867af46666e31739d2: no matching signatures:
            checking expiry on certificate with bundle: certificate expired before signatures were entered in log: 2023-01-02T00:20:01Z is before 2023-01-02T14:37:07-08:00:
```

However, I was wondering why only certain tests failed, and this was the only one without `ctlog`.  Adding that back (since this publishes to Rekor) lets things pass:
```yaml
    ctlog:
      url: https://rekor.sigstore.dev
```

**Version**

I believe that things are fine in the latest cut release, but I assume that something about the new `TrustRoot` handling at HEAD has caused the path where `ctlog` is unspecified to be broken.

🚨  **_WE SHOULD FIX THIS BEFORE THE NEXT RELEASE_** 🚨
