### ISSUE TITLE
If namespace is given to secret ref and it's not the same as in the policy-controller namespace, it should fail.

### ISSUE THREAD

**Issue by vaikas** [sigstore/policy-controller#578]
**Description**

User tried to create this CIP:
```
apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: tekton-attestation
spec:
  images:
  - glob: "quay.io/raffaelespazzoli/**"
  authorities:
  - name: static-key
    key:
      secretRef:
        namespace: openshift-pipelines
        
```

And it did not Fail at creation time. We should make sure that we reject if namespace for secretref is not the same as the one where the policy-controller was installed.

**Version**
