### ISSUE TITLE
Simple policy to require a signature

### ISSUE THREAD

**Issue by mlbiam** [sigstore/policy-controller#742]
**Question**

In previous releases I used the following policy to simply require a signature:

```yaml
apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: keyless
spec:
  images:
  - glob: "**"
  authorities:
  - name: keyless
    keyless:
      url: "https://fulcio.sigstore.dev"
```

However, with:

```
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
policy-controller       cosign-system   1               2023-04-20 11:48:27.712902 -0400 EDT    deployed        policy-controller-0.5.7 0.7.0 
```

I get this error when trying to deploy: `the ClusterImagePolicy "keyless" is invalid: spec.authorities[0].keyless.identities: Invalid value: "null": spec.authorities[0].keyless.identities in body must be of type array: "null"`

I tried updating with an empty array:

```yaml
apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: keyless
spec:
  images:
  - glob: "**"
  authorities:
  - name: keyless
    keyless:
      identities: []
      url: "https://fulcio.sigstore.dev"
```

but now get the error `Error from server (BadRequest): error when creating "/tmp/policy.yaml": admission webhook "validating.clusterimagepolicy.sigstore.dev" denied the request: validation failed: missing field(s): spec.authorities[0].keyless.identities`

What do I need for a minimum policy to verify there is a signature?

**Comment by hectorj2f** [comment]
@mlbiam This is similar to cosign verification, you need to specify the identities. Look at our examples or testdata. `identites` are required, e.g.

```
  authorities:
  - name: keyless
    keyless:
      identities:
      - issuer: https://accounts.google.com
        subject: blablalbla@sigstore.dev
```

**Comment by mlbiam** [comment]
So there's no way to write a policy that says "accept anything that is signed"?

**Comment by hectorj2f** [comment]
@mlbiam Accept anything signing without verifying the identity is similar to accept anything not signed.

**Comment by mlbiam** [comment]
> Accept anything signing without verifying the identity is similar to accept anything not signed.

In a production environment you're probably right, but from a training and learning standpoint it's very valuable to be able to start with the most open possible and take incremental steps is a great way to learn how this incredible complex and nuanced top works.

**Comment by hectorj2f** [comment]
Okay, knowing that now! I can propose to use this CIP 


```
apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: keyless
spec:
  images:
  - glob: "**"
  authorities:
  - name: keyless
     keyless:
        identities:
        - issuerRegExp: ".*"
           subjectRegExp: ".*"
```
or which allow everything: 

```
apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: image-policy-static-pass
spec:
  images:
  - glob: "**"
  authorities:
  - static:
      action: pass
``` 

Policy-controller also has a field `mode` that you can set to `warn` for testing purposes if you prefer:

```

```
apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: keyless
spec:
  mode: warn
  images:
  - glob: "**"
  authorities:
  - name: keyless
     keyless:
        identities:
        - issuerRegExp: ".*"
           subjectRegExp: ".*"
```

**Comment by mlbiam** [comment]
minor change to fix the formatting:

```yaml
apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: keyless
spec:
  images:
  - glob: "**"
  authorities:
  - name: keyless
    keyless:
      identities:
      - issuerRegExp: ".*"
        subjectRegExp: ".*"
```
