### ISSUE TITLE
Enable warning/complain-mode instead of rejection

### ISSUE THREAD

**Issue by JAORMX** [sigstore/policy-controller#98]
**Description**

`ClusterImagePolicy` objects already provide a lot of flexibility in terms of allowing images from certain organizations and configuring extensively the authorities to trust for others. While the current supported scenarios are a great end-state, the transition period becomes a little complicated. e.g. an organization that's starting to adopt signed images might want to do so gradually.

In order to promote signed images while still allowing folks to deploy, the proposal is to enable a warning mode or complain mode.

The mode would be an attribute of the `spec`, and could contain the values `enforce` or `warn`. Any authorities specified in the spec would still be evaluated, but validation wouldn't fail if the signatures are missing.

A relevant CIP would look as follows:

```
apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: metal-toolbox-signed
spec:
  mode: warn
  images:
    - glob: "ghcr.io/metal-toolbox/**"
  authorities:
    - keyless:
        url: https://fulcio.sigstore.dev
```

Warnings would be issued using Kubernetes' warning feature [1], where we can pass a list of warnings to the `AdmissionReview` response, which will in turn be interpreted and exposed to the caller.

Support for warnings is already present in the Knative `pkg` module which is used extensively in `policy-controller` [2]. The current implementation relies on the field error abstraction which is already used by the policy webhook, so it's a matter of setting the appropriate level to make this work.

Further iterations could also take into use audit annotations [3], but support for this would be required in the Knative libraries first.

Finally, in order to give operators further visibility on the progress of signed container image adoption, we could introduce metrics that output the number of warnings that the webhook has issued.

[1] https://kubernetes.io/blog/2020/09/03/warnings/#admission-webhooks
[2] https://github.com/knative/pkg/blob/main/apis/field_error.go#L43
[3] https://kubernetes.io/blog/2020/09/03/warnings/#audit-annotations
